spring:
  application:
    name: service-product
  data:
    mongodb:
      database: bootcamp_product_db
      host: localhost
      port: 8901
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8001
message:
  path-product: /api/v1/products
  path-productType: /api/v1/productTypes
  uri: /api/v1/productTypes/